export const TENANT_ID="TENANT ID";
export const EMAIL="EMAIL";
export const LAST_LICENSE_REQUEST="LAST LICENSE REQUEST";
export const NO_OF_LICENSE_REQUESTED="NO OF LICENSE REQUESTED";
export const LAST_USER_LOGIN ="LAST USER LOGIN";
export const TRIAL_EXPIRY="TRAIL EXPIRY";
export const EXTEND_TRIAL="EXTEND TRIAL"